# VARABLE IN PYTHON
#-----------------------------------------------------------------------------
# ->TO STORE THE VALUE OF AN ELEMENT 
# ->WE CAN CREATE AN VARIABLE BY USING ALPHA NUMARIC CHARACTER [ A-Z,a-z,0-9]
# ->WE CANT START AN VARIABLE BY USING DIGITS [0-9]
# ->WE CANT USE SPECIAL SYMBOLS [@,#,!,$,%,^,&,*] EXPET['_']
# -> IT IS A CASE SENSTIVE LANGUAGE
# EXAMPLE 1
NAVEEN=145
print(NAVEEN)
#EXAMPLE 2
REDDIE=12.423
print(REDDIE)
#EXAMPLE 3
VAMSI=44
print(VAMSI)
# example 4
sai=546
print(sai)
#example 5
janu=143
print(janu)
# example 6
prakash=909
print(prakash)
# example 7
raju=00
print(raju)