#DATATYPES:  ADATATYPE IS A CLASSIFICATION OF DATA BASED ON ITS FORMAT,SIZE. DATATYPES DETERMINE THE TYPE OF VALUE AVARIABLE CAN HOLD........
# INTEGER :IT CAN STORE THE VALUES - INFINITY TO +INFINITY
# A=1 WHERE = IS A ASSIGNMENT
#EXAMPLE PROGRAMS IN INTEGER
 # example 1
A=12
print(1)
print(A)
print(type(A))
# example 2
naveen=6453
print(naveen)
print(type(naveen))
# example 3
sai=224
print(sai)
# example 4
janu=2354
print(janu) 
# example 5
jhansi=146
print(jhansi)
# example 6
teks=57757587
print(teks)
# example 7
hello=753687
print(hello)
# example 8
nani=85435
print(nani)
# example 9
kiran=989898
print(kiran)
# example 10
raju=9302
print(raju)
# example 11
king=675
print(king)




#float
# example 1
a=1.53
print(a)

# example 2
sai=456.55
print(sai)
# example 3
kushi=535.44645
print(kushi)
# example 4

prasad=4567.83566
print(prasad)
# example 5

satya=3586.6789
print(satya)
# example 6
juuu=1423.5876342
print(juuu)

# example 7
joe=987.4327
print(joe)


# example 8
babu=67.876565
print(babu)

# example 9
oye=756.56
print(oye)

# example 10
hi=76.6583356
print(hi)

#complex number
# example 1
hlo=3+4j
print(hlo)

# example 2
ma=6+0j
print(ma)

# example 3
kaa=56+6j
print(kaa)
# example 4
baa=65+5j
print(baa)

# example 5
bava=56+0j
print(bava)

# example 6
bro=56+578j
print(bro)

# example 7 
pi=6+53j
print(pi)

# example 8
niill=87+0j
print(niill)

# example 9
repeat=35+9j
print(repeat)

# example 10
thenn=75+7j
print(thenn)



#bollean


print(12>5)

print(1>5)

print(2>5)

print(129>658)

print(19>68)

print(129<58)

print(129<658)


print(53>2)

print(547<2436568)

a=print(343<421356)

# int to float and     float to int

age=80.56
con_age=int(age)
print(con_age)
print(type(con_age))


janu=46.645
n_janu=int(janu)
print(n_janu)


jhaa=64.09
n_jhaa=int(jhaa)
print(n_jhaa)



jhan=54.75
n_jhan=int(jhan)
print(n_jhan)

teju=87.12
n_teju=int(teju)
print(n_teju)



hmmm=75.6457
n_hmmm=int(hmmm)
print(n_hmmm)
k_n_hmmm=float(n_hmmm)
print(k_n_hmmm)



kk=345.5467
n_kk=int(kk)
print(n_kk)
m_n_kk=float(n_kk)
print(m_n_kk)
print(type(kk))
print(type(n_kk))


thee=546
m_thee=float(thee)
print(m_thee)



hiii=67
m_hiii=float(hiii)
print(m_hiii)



hy='7898'
i_hy=float(hy)
ir_hy=complex(i_hy)
print(ir_hy)
print(i_hy)
print(type(i_hy))
print(type(hy))
print(type(ir_hy))


hiii=67
m_hiii=str(hiii)
print(m_hiii)
print(type(m_hiii))